// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgadzyzkparyrznqsvzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnYWR6eXprcGFyeXJ6bnFzdnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzUzNjIsImV4cCI6MjA3MTM1MTM2Mn0.6V6N5-ZEwRwDAyKiy93HANPUrmn4J_h1VhPlD8OjUK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});